# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: boxer

builds:
  - id: boxer
    builder: rust
    binary: boxer
    dir: .
    tool: cross
    command: build
    targets:
      - x86_64-unknown-linux-musl
      - aarch64-unknown-linux-musl
    flags:
      - --release

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      boxer-linux-
      {{- if eq .Arch "amd64" }}x64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}

  - id: bare
    formats:
      - binary
    name_template: >-
      boxer-linux-
      {{- if eq .Arch "amd64" }}x64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}

dockers:
  - id: boxer-amd64
    ids:
      - boxer
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/bonisoft3/boxer:{{ .Version }}-amd64"
      - "ghcr.io/bonisoft3/boxer:latest-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--target=goreleaser"
      - "--platform=linux/amd64"

  - id: boxer-arm64
    ids:
      - boxer
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/bonisoft3/boxer:{{ .Version }}-arm64"
      - "ghcr.io/bonisoft3/boxer:latest-arm64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--target=goreleaser"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/bonisoft3/boxer:{{ .Version }}"
    image_templates:
      - "ghcr.io/bonisoft3/boxer:{{ .Version }}-amd64"
      - "ghcr.io/bonisoft3/boxer:{{ .Version }}-arm64"

  - name_template: "ghcr.io/bonisoft3/boxer:latest"
    image_templates:
      - "ghcr.io/bonisoft3/boxer:latest-amd64"
      - "ghcr.io/bonisoft3/boxer:latest-arm64"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: bonisoft3
    name: boxer
  draft: false
  prerelease: auto
  mode: replace
  make_latest: true
  name_template: "boxer {{ .Version }}"
