# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: boxer

builds:
  - id: boxer
    builder: prebuilt
    goos:
      - linux
    goarch:
      - amd64
    prebuilt:
      path: target/x86_64-unknown-linux-musl/release/boxer

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "boxer-linux-x64"

  - id: bare
    formats:
      - binary
    name_template: "boxer-linux-x64"

dockers:
  - id: boxer-amd64
    ids:
      - boxer
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/bonisoft3/boxer:{{ .Version }}"
      - "ghcr.io/bonisoft3/boxer:latest"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--target=goreleaser"
      - "--platform=linux/amd64"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: bonisoft3
    name: boxer
  draft: false
  prerelease: auto
  mode: replace
  make_latest: true
  name_template: "boxer {{ .Version }}"
