include:
- path: ./compose.bayt.yaml
  required: false
services:
  setup:
    extends:
      file: ./compose.setup.yaml
      service: services_boxer-setup
  build:
    extends:
      file: ./compose.build.yaml
      service: services_boxer-build
  integrate:
    extends:
      file: ./compose.integrate.yaml
      service: services_boxer-integrate
