services:
  services_boxer-build:
    build:
      additional_contexts:
        bayt-runtime: ../../../plugins/bayt
        services_boxer-setup: service:services_boxer-setup
      context: ..
      dockerfile: .bayt/Dockerfile.build
      target: build
    image: bayt-services_boxer-build:latest
