# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
FROM services_boxer-setup AS build
WORKDIR /monorepo/services/boxer
COPY --link --parents src/**/* Cargo.toml Cargo.lock ./
RUN ["mise", "x", "--", "cargo", "build"]
COPY --link Taskfile.yml ./Taskfile.yml
COPY --link .bayt/Taskfile.yml .bayt/Taskfile.build.yaml .bayt/bayt.build.json .bayt/init.gradle.kts ./.bayt/
